<<<<<<< HEAD
# Generated by Django 2.2.3 on 2019-08-03 08:58

from django.db import migrations, models
=======
# Generated by Django 2.2.3 on 2019-08-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 5aa90ef8167f727ba376a25221492cbcf025838c


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 5aa90ef8167f727ba376a25221492cbcf025838c
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=20)),
                ('interest', models.CharField(choices=[('FAHION', '패션'), ('MEDIA', '미디어'), ('FOOD', '음식'), ('ETC', '기타')], max_length=15)),
=======
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
                ('full_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gugudog.Service')),
            ],
        ),
        migrations.CreateModel(
            name='GuDogService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gugudog.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.ManyToManyField(to='gugudog.GuDogService')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 5aa90ef8167f727ba376a25221492cbcf025838c
            ],
        ),
    ]
