# Generated by Django 2.2.3 on 2019-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=20)),
                ('interest', models.CharField(choices=[('FAHION', '패션'), ('MEDIA', '미디어'), ('FOOD', '음식'), ('ETC', '기타')], max_length=15)),
            ],
        ),
    ]
