# Generated by Django 2.2.3 on 2019-08-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0003_service_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='full_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gugudog.Service'),
        ),
    ]
