# Generated by Django 2.2.4 on 2019-08-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0003_auto_20190804_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzimservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ZZservice', to='gugudog.Service'),
        ),
    ]
