# Generated by Django 2.2.4 on 2019-08-04 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gugudog', '0004_auto_20190804_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='zzim_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
