# Generated by Django 2.2.4 on 2019-08-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0005_gudogservice_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gudogservice',
            name='register_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
