# Generated by Django 2.2.4 on 2019-08-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0008_interest_interestservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
