# Generated by Django 2.2.4 on 2019-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0009_auto_20190805_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
