# Generated by Django 2.2.4 on 2019-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0010_category_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
