# Generated by Django 2.2.4 on 2019-08-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0011_service_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to='logo_images/'),
        ),
    ]
