# Generated by Django 2.2.4 on 2019-08-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0015_auto_20190806_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='logo_image',
            new_name='image',
        ),
    ]
