# Generated by Django 2.2.4 on 2019-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugudog', '0016_auto_20190806_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
